### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by mwagner1886** [GENIVI/vehicle-edge#21]
Broken link in
https://github.com/GENIVI/vehicle-edge/tree/develop/docker-compose, section "Setup":

"For further information how to build the images (especially, if you are working behind a proxy), please see here"

Link behind "here" returns a 404.

**Comment by mariaivanova-git** [comment]
Thank you for helping us improve our documentation. We'll update it soon.

**Comment by SebastianSchildt** [comment]
Fixed in #23
