### ISSUE TITLE
Setup instructions & run.sh are outdated

### ISSUE THREAD

**Issue by PhilippMundhenk** [GENIVI/vehicle-edge#32]
I tried to get this set up by following https://github.com/GENIVI/vehicle-edge/tree/develop/docker-compose

Both the manual way and the run.sh refer to "<any folder>/src/sdk/javascript/lib/boschio.iotea-<version>.tgz" i the IoTEA repo. However, the lib folder and *.tgz file do not exist.

**Comment by llakie** [comment]
Was potentially fixed during the last merge. Can you please re-check?

**Comment by llakie** [comment]
Please wait for the PR #33 to merged. Here we cover many issues concerning the automated startup of the stack. We now support the fully automated Kuksa.VAL configuration creation for Windows PCs.
